In [2]:
from numpy.ma.core import identity
%pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 1.5 MB/s  0:00:03 eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
np.full((5,3), 3.14, dtype=float)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [7]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [8]:
np.arange(1, 5, dtype=int)

array([1, 2, 3, 4])

In [10]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [16]:
identity_matrix = np.eye(5)
print(identity_matrix)
print(type(identity_matrix[0][1]))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<class 'numpy.float64'>
